---
openapi: "3.0.2"

info:
  $ref: local/info.yaml

servers:
  $ref: local/servers.yaml

paths:
  $ref: local/paths.yaml

x-tagGroups:
  - name: Devices
    tags:
      - Devices
      - Device State
      - Device Properties
      - Device Actions
      - Device Remote Address
      - Device Reload
      - Power Cycle State
  - name: Commands
    tags:
      - Device Commands
      - Device Command Signal
      - Device Command Transmit
  - name: Groups
    tags:
      - Groups
      - Group Devices
      - Group State
      - Group Properties
      - Group Actions
  - name: Scenes
    tags:
      - Scenes
  - name: Schedules
    tags:
      - Device Schedules
      - Group Schedules 
      - Scene Schedules
  - name: Virtual Remote Control
    tags:
      - Virtual Remote Control
  - name: Sidekick
    tags:
      - Sidekick
      - Sidekick Learn
      - Keystream
      - Channels
  - name: Weather Sensor
    tags:
      - Weather Sensor
      - Weather Sensor Properties
      - Weather Sensor State
      - Weather Sensor Test
  - name: Bridge
    tags:
      - Bridge
  - name: Signals
    tags:
      - Transmit
      - Scan
      - Scan Result
      - Rssi
  - name: API
    tags:
      - Token
      - MQTT
      - BPUP
      - HomeKit
  - name: Network
    tags:
      - Wi-Fi Scan
      - Wi-Fi Station
      - Ethernet
      - Network Watchdog
  - name: System
    tags:
      - Upgrade
      - Version
      - Backup
      - Reset
      - Reboot
      - Time
      - Power
      - Locale
  - name: Debug
    tags:
      - Database
      - LiveLog
      - LEDs
      - WiFi
      - RF Manager
